const express = require('express')
const bodyParser = require('body-parser')
const authRouter = require('./routes/auth')
const usersRouter = require('./routes/users')
const videosRouter = require('./routes/videos')
const commentsRouter = require('./routes/comments')
const indexRouter = require('./routes/index')
const errorHandler = require('./middleware/error-handler')
const authHandler = require('./middleware/auth-handler')
const sessionMiddleware = require('./middleware/session')
require('./mongo-connection')

const app = express()
app.use(bodyParser.json())
app.use(sessionMiddleware)
app.use('/auth', authRouter)
app.use('/users', authHandler, usersRouter)
app.use('/videos', authHandler, videosRouter)
app.use('/comments', authHandler, commentsRouter)
app.use('/', indexRouter)

app.use(errorHandler)

app.listen(3000, () => {
  console.log('Server is listening port 3000')
})
